name: 🔗 Check for Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 0'  # Runs every Sunday at 3:00 AM UTC

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Install lychee (Rust-based link checker)
        uses: lycheeverse/lychee-action@v1.6.1

      - name: 🔎 Run lychee to check all HTML and markdown files
        run: |
          lychee --verbose --no-progress --exclude-all-private --timeout 20 "**/*.html" "**/*.md"

